version: '2'
services:
  to_do_app-app:
    image: to_do_app
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://to_do_app-mysql:3306/to_do_app?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://to_do_app-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://to_do_app-elasticsearch:9200
    ports:
      - 8080:8080
  to_do_app-mysql:
    extends:
      file: mysql.yml
      service: to_do_app-mysql
  to_do_app-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: to_do_app-elasticsearch
